[package]
name = "yek"
version = "0.3.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = "4.4"
ignore = "0.4"
regex = "1.10"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10"
time = "0.3"
toml = "0.8"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["time", "local-time"] }
walkdir = "2.4"

[dev-dependencies]
assert_cmd = "2.0"
chrono = "0.4"
predicates = "3.0"
tempfile = "3.9"
