output_dir = "./repo-serialized"

ignore_patterns = [
    "^repo-serialized/",
    "^.*\\.txt$",
    "^tests/.*",
    "^scripts/.*",
    "^.github/.*",
    "^.cargo/.*",
    "^benchmarks/",
    "^src/defaults\\.rs$",
    "^\\.github/.*$",
    "README.md",
    "CHANGELOG.md",
    "^LICENSE$",
    "^README$",
    "^askai.yaml$"
]

[[priority_rules]]
score = 100
pattern = "^src/"

[[priority_rules]]
score = 70
pattern = "^src/lib/"

[[priority_rules]]
score = 70
pattern = "^test/"

[[priority_rules]]
score = 30
pattern = "^scripts/"

[[priority_rules]]
score = 10
pattern = "^src/defaults\\.rs$" 